teleport-delay: 3000
cancel-timeout: 350
language: "ru"

languages:
  en:
    teleportBlockName: "Teleportation Block"
    teleportCompassName: "Teleportation Compass"

  ru:
    teleportBlockName: "Блок телепортации"
    teleportCompassName: "Компас телепортации"
